package errors

import "errors"

var (
	ErrInvalidCredentials     = errors.New("invalid credentials")
	ErrUserExists             = errors.New("user already exists")
	ErrNotFound               = errors.New("not found")
	ErrUnauthorized           = errors.New("unauthorized")
	ErrBVNNotFound            = errors.New("bvn not found")
	ErrNINNotFound            = errors.New("nin not found")
	ErrInvalidNIN             = errors.New("invalid nin")
	ErrInvalidBVN             = errors.New("invalid bvn")
	ErrPhoneNotFound          = errors.New("phone not found")
	ErrPhoneMismatch          = errors.New("phones do not match")
	ErrEmailNotFound          = errors.New("email not found")
	ErrNINAndBVNMismatch      = errors.New("nin and bvn do not match")
	ErrPasswordMismatch       = errors.New("passwords do not match")
	ErrTransactionPinMismatch = errors.New("transaction pins do not match")
	ErrMissingDeviceID        = errors.New("missing device id")
	ErrMissingUserID          = errors.New("missing user id")
	ErrDeviceNotAllowed       = errors.New("device not allowed")
	ErrInvalidSession         = errors.New("invalid session")
	ErrMissingOTP             = errors.New("otp is required")
	ErrInvalidOTP             = errors.New("invalid otp")
	ErrMissingPublicKey       = errors.New("public key is required")
	ErrInvalidPhone           = errors.New("invalid phone")
	ErrInvalidDateFrom        = errors.New("invalid date from")
	ErrInvalidDateTo          = errors.New("invalid date to")
	ErrInvalidDateRange       = errors.New("invalid date range")
	ErrUnderaged              = errors.New("user is underaged")
	ErrInvalidLoanAmount      = errors.New("invalid loan amount")
	ErrInvalidLoanProduct     = errors.New("invalid loan product")
	ErrIncompleteKYC          = errors.New("incomplete kyc")
	ErrIneligibleBusinessAge  = errors.New("ineligible business age")
	ErrIneligibleForLoan      = errors.New("ineligible for loan")
	ErrInvalidBusinessValue   = errors.New("invalid business value")
	ErrInvalidLoanTerm        = errors.New("invalid loan term")
	ErrInvalidSavingsAmount   = errors.New("invalid savings amount")
)
